// <auto-generated />
using System;
using CalTrek.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CalTrek.Migrations
{
    [DbContext(typeof(CalTrekContext))]
    partial class CalTrekContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CalTrekApp.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumRodjenja");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Drzava")
                        .IsRequired();

                    b.Property<string>("Grad")
                        .IsRequired();

                    b.Property<string>("Ime")
                        .IsRequired();

                    b.Property<string>("Prezime")
                        .IsRequired();

                    b.Property<string>("Spol")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Korisnik");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Korisnik");
                });

            modelBuilder.Entity("CalTrekApp.Models.Obrok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Kalorije");

                    b.Property<float>("Masti");

                    b.Property<string>("Naziv")
                        .IsRequired();

                    b.Property<float>("Proteini");

                    b.Property<float>("Ugljikohidrati");

                    b.HasKey("Id");

                    b.ToTable("Obrok");
                });

            modelBuilder.Entity("CalTrekApp.Models.Tjelovjezba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("BCPM");

                    b.Property<string>("Naziv")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Tjelovjezba");
                });

            modelBuilder.Entity("CalTrekApp.Models.Klijent", b =>
                {
                    b.HasBaseType("CalTrekApp.Models.Korisnik");


                    b.ToTable("Klijent");

                    b.HasDiscriminator().HasValue("Klijent");
                });

            modelBuilder.Entity("CalTrekApp.Models.Strucnjak", b =>
                {
                    b.HasBaseType("CalTrekApp.Models.Korisnik");

                    b.Property<int>("GodineIskustva");

                    b.Property<int>("Tip");

                    b.ToTable("Strucnjak");

                    b.HasDiscriminator().HasValue("Strucnjak");
                });
#pragma warning restore 612, 618
        }
    }
}
